import { randomBytes, scryptSync } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

export function generateConfiguration({
  username = 'admin',
  password = randomBytes(18).toString('base64url'),
  controllerSecret = randomBytes(32).toString('hex'),
  salt = randomBytes(16).toString('hex'),
} = {}) {
  const cleanUsername = String(username).trim()
  if (!cleanUsername || /[\r\n=]/.test(cleanUsername)) throw new Error('管理员用户名无效')
  if (String(password).length < 16 || /[\r\n]/.test(String(password))) throw new Error('管理员密码至少需要 16 个字符')
  const passwordHash = scryptSync(String(password), salt, 64).toString('hex')
  const content = [
    '# Generated by npm run init. Do not commit this file.',
    'SUBSCRIPTION_MODE=native',
    'SUBSCRIPTION_USER_AGENT=mihomo/1.19.28',
    `MIHOMO_CONTROLLER_SECRET=${controllerSecret}`,
    `AUTH_USERNAME=${cleanUsername}`,
    `AUTH_PASSWORD_SALT=${salt}`,
    `AUTH_PASSWORD_SCRYPT=${passwordHash}`,
    'AUTH_COOKIE_SECURE=false',
    'AUTH_SESSION_IDLE_SECONDS=7200',
    'AUTH_SESSION_MAX_SECONDS=28800',
    'AUTH_SESSION_TOUCH_SECONDS=300',
    'AUTH_REMEMBER_IDLE_SECONDS=2592000',
    'AUTH_REMEMBER_MAX_SECONDS=2592000',
    'AUTH_SESSION_VERSION=1',
    '',
  ].join('\n')
  return { content, username: cleanUsername, password }
}

export async function initializeEnvironment({ root = projectRoot, force = false, username, password } = {}) {
  const envPath = path.join(root, '.env')
  if (!force) {
    try {
      await readFile(envPath, 'utf8')
      throw new Error(`已存在 ${envPath}；如需重新生成，请运行 npm run init -- --force`)
    } catch (error) {
      if (error?.code !== 'ENOENT') throw error
    }
  }
  const result = generateConfiguration({ username, password })
  await writeFile(envPath, result.content, { encoding: 'utf8', mode: 0o600 })
  return { ...result, envPath }
}

function envValue(content, key) {
  const match = String(content).match(new RegExp(`^${key}=(.*)$`, 'm'))
  return match?.[1]?.trim() || ''
}

function setEnvValue(content, key, value) {
  const line = `${key}=${value}`
  const pattern = new RegExp(`^${key}=.*$`, 'm')
  return pattern.test(content) ? content.replace(pattern, () => line) : `${content.trimEnd()}\n${line}\n`
}

export async function resetPassword({ root = projectRoot, username, password = randomBytes(18).toString('base64url') } = {}) {
  const envPath = path.join(root, '.env')
  const existing = await readFile(envPath, 'utf8')
  const cleanUsername = String(username || envValue(existing, 'AUTH_USERNAME') || 'admin').trim()
  if (!cleanUsername || /[\r\n=]/.test(cleanUsername)) throw new Error('管理员用户名无效')
  if (String(password).length < 16 || /[\r\n]/.test(String(password))) throw new Error('管理员密码至少需要 16 个字符')
  const salt = randomBytes(16).toString('hex')
  const passwordHash = scryptSync(String(password), salt, 64).toString('hex')
  let content = setEnvValue(existing, 'AUTH_USERNAME', cleanUsername)
  content = setEnvValue(content, 'AUTH_PASSWORD_SALT', salt)
  content = setEnvValue(content, 'AUTH_PASSWORD_SCRYPT', passwordHash)
  const currentVersion = Number(envValue(content, 'AUTH_SESSION_VERSION') || 1)
  content = setEnvValue(content, 'AUTH_SESSION_VERSION', String(Number.isInteger(currentVersion) ? currentVersion + 1 : 2))
  await writeFile(envPath, content, { encoding: 'utf8', mode: 0o600 })
  return { envPath, username: cleanUsername, password }
}

async function main() {
  const force = process.argv.includes('--force')
  const passwordReset = process.argv.includes('--reset-password')
  if (force && passwordReset) throw new Error('--force 与 --reset-password 不能同时使用')
  const options = { username: process.env.PPM_INIT_USERNAME || undefined, password: process.env.PPM_INIT_PASSWORD || undefined }
  const result = passwordReset ? await resetPassword(options) : await initializeEnvironment({ force, ...options })
  console.log(`${passwordReset ? '已安全重置认证信息' : '已生成'} ${result.envPath}`)
  console.log(`管理账号：${result.username}`)
  console.log(`管理密码：${result.password}`)
  console.log('请立即保存密码；配置文件只保存不可逆的 Scrypt 哈希。')
  if (passwordReset) console.log('下一步：docker compose up -d --force-recreate proxy-port-manager')
  else {
    console.log('下一步：docker compose config')
    console.log('然后运行：docker compose build --pull')
    console.log('最后运行：docker compose up -d')
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch(error => { console.error(error.message); process.exitCode = 1 })
}
